# Generated by Django 4.1.9 on 2023-06-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0003_alter_user_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
