# Generated by Django 4.1.9 on 2023-06-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypro1', '0005_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(default='todo', max_length=100),
        ),
    ]
